buildDeps:
  - jdk8
  - maven3

steps:
  - description: "Installing ant"
    commands:
      - wget https://www.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.zip
      - unzip -qq apache-ant-1.10.5-bin.zip

  - description: "Running ant build"
    commands:
      - apache-ant-1.10.5/bin/ant

  - description: "Changing POM version"
    commands:
      - set-maven-versions --root $WORKSPACE --version "$(if [ $GIT_BRANCH == 2.12.1-hs ]; then echo 2.12.$MODULE_BUILD_NUMBER-hubspot; else echo 2.12.$MODULE_BUILD_NUMBER-hubspot-$GIT_BRANCH; fi)"

  - description: "Uploading JAR to Nexus"
    commands:
      - mvn -B
            org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy-file
            -DrepositoryId=s3
            -Durl=s3://hubspot-maven-artifacts-prod/releases
            -DpomFile=pom.xml
            -Dfile=build/jars/spymemcached-2.11.1.jar
            -Dsources=build/sources/spymemcached-2.11.1.jar
