buildpack:
  name: Blazar-Buildpack-Java-prebuilt

before:
  - description: "Installing ant"
    commands:
      - curl https://dlcdn.apache.org/ant/binaries/apache-ant-1.10.14-bin.zip --output apache-ant-1.10.14-bin.zip
      - unzip -qq apache-ant-1.10.14-bin.zip

  - description: "Running ant build"
    commands:
      - apache-ant-1.10.14/bin/ant

  - description: "Copy files"
    commands:
      - mkdir spymemcached-2.12.1
      - cp pom.xml spymemcached-2.12.1/pom.xml
      - cp build/jars/spymemcached-no-version.jar spymemcached-2.12.1/main.jar
      - cp build/sources/spymemcached-no-version.jar spymemcached-2.12.1/sources.jar
      - rm -rf apache-ant-1.10.14
      - rm -rf build
